// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 Khalil Warren — capillary
//
// driver_export.ts — turn a traced functional-test run into portable driver
// artifacts ("run skeletons"). Capillary explores agentically ONCE; the proven
// path then exports as:
//
//   1. A deterministic Playwright spec — runs in any CI, no capillary, no LLM.
//   2. An agent runsheet — model-agnostic instructions a dev can hand to any
//      coding agent (Claude, Copilot, whatever) to reproduce or port the run
//      (e.g. to Selenium) with the goal, ordered actions, reasons and
//      verifications intact.
//
// Pure functions over the persisted record; exported for direct unit testing.

import { RetvCdpRunRecord, RetvCdpTraceCycle } from "../domain/entities.ts";

function str(value: unknown): string {
  return typeof value === "string" ? value : String(value ?? "");
}

/** Source-safe string literal (backslashes, quotes, newlines escaped). */
function lit(value: unknown): string {
  return JSON.stringify(str(value));
}

interface FlatCall {
  cycle: number;
  tool: string;
  args: Record<string, unknown>;
  reason: string;
  /** False when the original run's matching step failed. */
  ok: boolean;
}

/** Flatten trace cycles into an ordered action list, pairing steps' outcomes. */
function flattenCalls(cycles: RetvCdpTraceCycle[]): FlatCall[] {
  const calls: FlatCall[] = [];
  for (const cycle of cycles) {
    cycle.toolCalls.forEach((call, index) => {
      calls.push({
        cycle: cycle.cycle,
        tool: call.tool,
        args: (call.args ?? {}) as Record<string, unknown>,
        reason: call.reason ?? "",
        ok: cycle.steps[index]?.ok ?? true,
      });
    });
  }
  return calls;
}

/** One Playwright statement per tool call; unknown tools become comments. */
function playwrightLine(call: FlatCall): string {
  const a = call.args;
  switch (call.tool) {
    case "navigate":
      return `await page.goto(${lit(a.url)});`;
    case "waitForSelector":
      return `await page.locator(${lit(a.selector)}).first().waitFor();`;
    case "click":
      return `await page.locator(${lit(a.selector)}).first().click();`;
    case "type":
      return `await page.locator(${lit(a.selector)}).first().fill(${lit(a.text ?? a.value)});`;
    case "extractText":
      return `console.log(await page.locator(${lit(a.selector)}).first().innerText());`;
    case "assertText":
      // Capillary asserts whitespace-normalized; toContainText matches that.
      return `await expect(page.locator(${lit(a.selector)}).first()).toContainText(${
        lit(a.includes ?? a.equals)
      });`;
    case "evaluate":
      return `await page.evaluate(${lit(a.expression)});`;
    case "readPage":
      return `// readPage: agent-only observation step — no runtime action needed.`;
    case "screenshot":
      return `await page.screenshot({ path: \`cycle-${call.cycle}.png\`, fullPage: true });`;
    default:
      return `// unsupported tool ${call.tool}: ${JSON.stringify(a)}`;
  }
}

/** Deterministic Playwright spec generated from a traced run. */
export function buildPlaywrightSpec(record: RetvCdpRunRecord): string {
  const cycles = record.trace?.cycles ?? [];
  const calls = flattenCalls(cycles);
  const lines: string[] = [];
  lines.push(`// ${record.runId} — generated by Capillary from a traced functional-test run.`);
  lines.push(`// Goal: ${record.goal.replaceAll("\n", " ")}`);
  lines.push(`// Origin: ${record.allowedOrigin} · ${record.startedAt}`);
  lines.push(
    `// Assertions are whitespace-normalized upstream; toContainText matches that behavior.`,
  );
  lines.push(`import { expect, test } from "@playwright/test";`);
  lines.push(``);
  lines.push(`test(${lit(record.goal.slice(0, 80) || record.runId)}, async ({ page }) => {`);

  let lastCycle = -1;
  for (const call of calls) {
    if (call.cycle !== lastCycle) {
      lines.push(`  // --- cycle ${call.cycle} ---`);
      lastCycle = call.cycle;
    }
    if (call.reason) {
      lines.push(`  // ${call.reason.replaceAll("\n", " ")}`);
    }
    const statement = playwrightLine(call);
    if (!call.ok) {
      // Failed in the original run: exported disabled, with the record kept —
      // silently replaying a known failure would launder it into a pass.
      lines.push(`  // FAILED in the recorded run — review before enabling:`);
      lines.push(`  // ${statement}`);
    } else {
      lines.push(`  ${statement}`);
    }
  }

  lines.push(`});`);
  lines.push(``);
  return lines.join("\n");
}

/**
 * Model-agnostic runsheet: everything another agent needs to reproduce (or
 * port) the run — goal, origin, ordered actions with intent, verifications,
 * findings, and the original outcome for comparison.
 */
export function buildAgentRunsheet(record: RetvCdpRunRecord): string {
  const cycles = record.trace?.cycles ?? [];
  const calls = flattenCalls(cycles);
  const lines: string[] = [];
  lines.push(`# Run Skeleton — ${record.runId}`);
  lines.push(``);
  lines.push(
    `Generated by Capillary from a traced functional-test run. Hand this file to any ` +
      `coding agent (Claude, Copilot, …) or engineer to reproduce the run, or to port it ` +
      `to another driver (Playwright spec ships alongside; Selenium et al. translate 1:1 ` +
      `from the action table).`,
  );
  lines.push(``);
  lines.push(`## Goal`);
  lines.push(record.goal);
  lines.push(``);
  lines.push(`## Target`);
  lines.push(`- Origin: ${record.allowedOrigin}`);
  lines.push(`- Recorded: ${record.startedAt} · ${record.cycleCount} cycles`);
  lines.push(
    `- Original outcome: ${record.stopReason} · goalAchieved=${record.goalAchieved} · ` +
      `functionalTestSucceeded=${record.functionalTestSucceeded}`,
  );
  lines.push(``);
  lines.push(`## Actions (in order)`);
  lines.push(``);
  lines.push(`| # | Cycle | Action | Arguments | Intent | Recorded result |`);
  lines.push(`|---|-------|--------|-----------|--------|-----------------|`);
  calls.forEach((call, index) => {
    const args = JSON.stringify(call.args).replaceAll("|", "\\|");
    const reason = (call.reason || "—").replaceAll("|", "\\|").replaceAll("\n", " ");
    lines.push(
      `| ${index + 1} | ${call.cycle} | ${call.tool} | \`${args}\` | ${reason} | ${
        call.ok ? "ok" : "FAILED"
      } |`,
    );
  });
  lines.push(``);
  lines.push(`## Verification notes`);
  lines.push(
    `- Text assertions are whitespace-normalized (collapse runs of whitespace, trim) ` +
      `on both sides before comparison.`,
  );
  lines.push(
    `- Steps marked FAILED failed in the recorded run — investigate before treating ` +
      `them as part of the happy path.`,
  );
  if (record.findings.length > 0) {
    lines.push(``);
    lines.push(`## Findings from the recorded run`);
    for (const finding of record.findings) {
      lines.push(`- ${finding}`);
    }
  }
  lines.push(``);
  return lines.join("\n");
}
